version: "2"

services:
  spark:
    image: docker.io/bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYSPARK_PYTHON=/opt/bitnami/python/bin/python
    ports:
      - "9080:8080"
      - "9081:8081"

    volumes:
      - .././cos-mock/raw:/data/raw/
      - .././cos-mock/refined:/data/curated/
    networks:
      - wiki_net
  spark-worker-1:
    image: docker.io/bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYSPARK_PYTHON=/opt/bitnami/python/bin/python
    volumes:
      - .././cos-mock/raw:/data/raw/
      - .././cos-mock/refined:/data/curated/
    networks:
      - wiki_net
  spark-worker-2:
    image: docker.io/bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYSPARK_PYTHON=/opt/bitnami/python/bin/python
    volumes:
      - .././cos-mock/raw:/data/raw/
      - .././cos-mock/refined:/data/curated/
    networks:
      - wiki_net

networks:
  wiki_net:
    name: wiki_net
